apiVersion: apps/v1
kind: Deployment
metadata:
  name: myreactapp
  labels:
    app: myreactapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myreactapp
  template:
    metadata:
      labels:
        app: myreactapp
    spec:
      serviceAccountName: default
      containers:
        - name: myreactapp
          image: rajesh7620/myreactapp:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: 3000
          readinessProbe:
            httpGet:
              path: /
              port: 3000
